version: 0.2

phases:
  install:
    commands:
      # Install dependencies needed for running test
      - npm install
      

      # Upgrade AWS CLI to the latest version
      - pip install --upgrade awscli
